"""
Pytest configuration and fixtures for Customer Feedback System tests.

This module provides shared fixtures and test configuration for the entire test suite.
"""

import pytest
from unittest.mock import MagicMock, patch, AsyncMock
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session
from sqlalchemy.pool import StaticPool
from datetime import datetime, timedelta, timezone
from uuid import uuid4
import uuid

# Import Base from the application's db module
from app.db.base import Base

# Import ALL models to ensure relationships are resolved
# This is critical for SQLAlchemy to properly set up foreign key relationships
from app.models.human import Human, Employee, Customer, Role, CustomerType
from app.models.ticket import Ticket, TicketCategory, TicketTemplate, SLAPolicy
from app.models.department import Department
from app.models.appointment import Appointment
from app.models.interaction import Message, Evaluate, Notification, Attachment
from app.models.interaction import MessageType
from app.models.sentiment import SentimentReport, SentimentDetail
from app.models.chatbot import ChatSession, ChatMessage
from app.models.ticketComment import TicketComment
from app.models.ticketHistory import TicketHistory
from app.models.escalationRule import EscalationRule
from app.models.tag import Tag
from app.models.systemSettings import SystemSettings
from app.models.system import AuditLog, FAQArticle
from app.core.constants import (
    TicketStatusConstants,
    HumanStatusEnum,
    MembershipTierEnum,
    AppointmentStatus,
    AppointmentConstants,
)
from app.core.security import get_password_hash


# ============================================================================
# Constants
# ============================================================================

# Real password hash for '321321' generated by bcrypt
SAMPLE_PASSWORD_HASH = "$2b$12$3pX9sevRZHfI0Vkg8gVzBOX8pUoIx811eVHSnR7jRi3QnZhsrNMXW"


# ============================================================================
# Database Fixtures
# ============================================================================

@pytest.fixture(scope="function")
def db_engine():
    """Create an in-memory SQLite database engine for testing."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    yield engine
    Base.metadata.drop_all(bind=engine)


@pytest.fixture(scope="function")
def db_session(db_engine) -> Session:
    """Create a new database session for each test."""
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=db_engine)
    session = SessionLocal()

    yield session

    session.rollback()
    session.close()


# ============================================================================
# Department and Role Fixtures
# ============================================================================

@pytest.fixture
def sample_department(db_session) -> Department:
    """Create a sample department for testing."""
    department = Department(
        id_department=uuid4(),
        name="Customer Support",
        description="Primary customer support department",
        is_active=True
    )
    db_session.add(department)
    db_session.commit()
    return department


@pytest.fixture
def sample_department_2(db_session) -> Department:
    """Create a second department for testing."""
    department = Department(
        id_department=uuid4(),
        name="Technical Department",
        description="Technical support department",
        is_active=True
    )
    db_session.add(department)
    db_session.commit()
    return department


@pytest.fixture
def sample_role_admin(db_session) -> Role:
    """Create admin role."""
    role = Role(role_name="Admin", description="System administrator")
    db_session.add(role)
    db_session.commit()
    return role


@pytest.fixture
def sample_role_manager(db_session) -> Role:
    """Create manager role."""
    role = Role(role_name="Manager", description="Department manager")
    db_session.add(role)
    db_session.commit()
    return role


@pytest.fixture
def sample_role_employee(db_session) -> Role:
    """Create employee role."""
    role = Role(role_name="Employee", description="Regular employee")
    db_session.add(role)
    db_session.commit()
    return role


@pytest.fixture
def sample_customer_type(db_session) -> CustomerType:
    """Create a customer type."""
    customer_type = CustomerType(
        type_name="Premium",
        description="Premium customer tier"
    )
    db_session.add(customer_type)
    db_session.commit()
    return customer_type


# ============================================================================
# User Fixtures (Using Real Password Hash for '321321')
# ============================================================================

@pytest.fixture
def sample_employee(
    db_session,
    sample_department,
    sample_role_admin
) -> Employee:
    """Create a sample employee for testing (Admin role)."""
    employee = Employee(
        id=uuid4(),
        username="employee1",
        email="employee1@example.com",
        password_hash=SAMPLE_PASSWORD_HASH,
        first_name="John",
        last_name="Doe",
        phone="1234567890",
        address="123 Main St",
        status=HumanStatusEnum.ACTIVE,
        type="employee",
        id_employee=uuid4(),
        id_department=sample_department.id_department,
        employee_code="EMP001",
        job_title="Support Agent",
        max_ticket_capacity=5,
        csat_score=4.5,
        hire_date=datetime.now().date(),
        role_name="Admin"
    )
    db_session.add(employee)
    db_session.commit()
    return employee


@pytest.fixture
def sample_employee_2(
    db_session,
    sample_department,
    sample_role_employee
) -> Employee:
    """Create a second employee for testing (Employee role)."""
    employee = Employee(
        id=uuid4(),
        username="employee2",
        email="employee2@example.com",
        password_hash=SAMPLE_PASSWORD_HASH,
        first_name="Jane",
        last_name="Smith",
        phone="0987654321",
        address="456 Oak Ave",
        status=HumanStatusEnum.ACTIVE,
        type="employee",
        id_employee=uuid4(),
        id_department=sample_department.id_department,
        employee_code="EMP002",
        job_title="Support Agent",
        max_ticket_capacity=3,
        csat_score=4.0,
        hire_date=datetime.now().date(),
        role_name="Employee"
    )
    db_session.add(employee)
    db_session.commit()
    return employee


@pytest.fixture
def sample_manager(
    db_session,
    sample_department,
    sample_role_manager
) -> Employee:
    """Create a manager employee for testing."""
    manager = Employee(
        id=uuid4(),
        username="manager1",
        email="manager1@example.com",
        password_hash=SAMPLE_PASSWORD_HASH,
        first_name="Mike",
        last_name="Manager",
        phone="5556667777",
        address="789 Manager Ave",
        status=HumanStatusEnum.ACTIVE,
        type="employee",
        id_employee=uuid4(),
        id_department=sample_department.id_department,
        employee_code="MGR001",
        job_title="Support Manager",
        max_ticket_capacity=10,
        csat_score=4.8,
        hire_date=datetime.now().date(),
        role_name="Manager"
    )
    db_session.add(manager)
    db_session.commit()
    return manager


@pytest.fixture
def sample_customer(
    db_session,
    sample_customer_type
) -> Customer:
    """Create a sample customer for testing."""
    customer = Customer(
        id=uuid4(),
        username="customer1",
        email="customer1@example.com",
        password_hash=SAMPLE_PASSWORD_HASH,
        first_name="Alice",
        last_name="Johnson",
        phone="1112223333",
        address="789 Pine Rd",
        status=HumanStatusEnum.ACTIVE,
        type="customer",
        id_customer=uuid4(),
        customer_code="KH260001",
        membership_tier=MembershipTierEnum.GOLD,
        timezone="Asia/Ho_Chi_Minh",
        customer_type="Premium"
    )
    db_session.add(customer)
    db_session.commit()
    return customer


@pytest.fixture
def sample_customer_pending(db_session, sample_customer_type) -> Customer:
    """Create a customer in pending status (for OTP verification testing)."""
    customer = Customer(
        id=uuid4(),
        username="pending_customer",
        email="pending@example.com",
        password_hash=SAMPLE_PASSWORD_HASH,
        first_name="Bob",
        last_name="Pending",
        phone="4445556666",
        address="321 Elm St",
        status=HumanStatusEnum.PENDING,
        type="customer",
        id_customer=uuid4(),
        customer_code="KH260002",
        membership_tier=MembershipTierEnum.STANDARD,
        timezone="Asia/Ho_Chi_Minh",
        customer_type="Premium"
    )
    db_session.add(customer)
    db_session.commit()
    return customer


# ============================================================================
# Ticket-Related Fixtures
# ============================================================================

@pytest.fixture
def sample_ticket_category(db_session, sample_department) -> TicketCategory:
    """Create a sample ticket category."""
    category = TicketCategory(
        id_category=uuid4(),
        name="Technical Support",
        description="Technical support requests",
        is_active=True,
        id_department=sample_department.id_department,
        auto_assign=True
    )
    db_session.add(category)
    db_session.commit()
    return category


@pytest.fixture
def sample_ticket_template(
    db_session,
    sample_ticket_category,
    sample_employee
) -> TicketTemplate:
    """Create a sample ticket template."""
    template = TicketTemplate(
        id_template=uuid4(),
        version=1,
        name="Bug Report Template",
        description="Template for bug reports",
        fields_config={
            "fields": [
                {"name": "steps_to_reproduce", "type": "text", "required": True},
                {"name": "expected_behavior", "type": "text", "required": True},
                {"name": "actual_behavior", "type": "text", "required": True},
            ],
            "severity": {"default_value": "Medium"}
        },
        is_active=True,
        is_deleted=False,
        id_category=sample_ticket_category.id_category,
        id_author=sample_employee.id_employee
    )
    db_session.add(template)
    db_session.commit()
    return template


@pytest.fixture
def sample_sla_policy(db_session) -> SLAPolicy:
    """Create a sample SLA policy."""
    sla = SLAPolicy(
        id_policy=uuid4(),
        policy_name="High Priority SLA",
        severity="High",
        max_resolution_days=1,
        is_active=True
    )
    db_session.add(sla)
    db_session.commit()
    return sla


@pytest.fixture
def sample_ticket(
    db_session,
    sample_customer,
    sample_employee
) -> Ticket:
    """Create a sample ticket for testing."""
    ticket = Ticket(
        id_ticket=uuid4(),
        title="Cannot login to account",
        custom_fields={"issue": "login problem"},
        status="New",
        severity="High",
        version=1,
        expired_date=datetime.utcnow() + timedelta(days=3),
        id_employee=None,  # Unassigned initially
        id_customer=sample_customer.id_customer,
        survey_sent=False
    )
    db_session.add(ticket)
    db_session.commit()
    return ticket


@pytest.fixture
def sample_ticket_assigned(
    db_session,
    sample_customer,
    sample_employee
) -> Ticket:
    """Create an assigned ticket in progress."""
    ticket = Ticket(
        id_ticket=uuid4(),
        title="Need help with feature X",
        custom_fields={"feature": "X"},
        status="In Progress",
        severity="Medium",
        version=1,
        expired_date=datetime.utcnow() + timedelta(days=5),
        id_employee=sample_employee.id_employee,
        id_customer=sample_customer.id_customer,
        survey_sent=False
    )
    db_session.add(ticket)
    db_session.commit()
    return ticket


@pytest.fixture
def sample_ticket_resolved(
    db_session,
    sample_customer,
    sample_employee
) -> Ticket:
    """Create a resolved ticket ready for closing."""
    ticket = Ticket(
        id_ticket=uuid4(),
        title="Issue with billing",
        custom_fields={"billing_cycle": "monthly"},
        status="Resolved",
        severity="Low",
        version=1,
        resolved_at=datetime.utcnow(),
        id_employee=sample_employee.id_employee,
        id_customer=sample_customer.id_customer,
        survey_sent=True
    )
    db_session.add(ticket)
    db_session.commit()
    return ticket


@pytest.fixture
def sample_ticket_closed(
    db_session,
    sample_customer,
    sample_employee
) -> Ticket:
    """Create a closed ticket for testing."""
    ticket = Ticket(
        id_ticket=uuid4(),
        title="Completed support request",
        custom_fields={"resolution": "completed"},
        status="Closed",
        severity="Low",
        version=1,
        resolved_at=datetime.utcnow() - timedelta(days=1),
        id_employee=sample_employee.id_employee,
        id_customer=sample_customer.id_customer,
        survey_sent=True
    )
    db_session.add(ticket)
    db_session.commit()
    return ticket


# ============================================================================
# Appointment Fixtures
# ============================================================================

@pytest.fixture
def sample_appointment(
    db_session,
    sample_ticket,
    sample_customer,
    sample_employee
) -> Appointment:
    """Create a sample appointment."""
    appointment = Appointment(
        id_appointment=uuid4(),
        id_ticket=sample_ticket.id_ticket,
        id_customer=sample_customer.id_customer,
        id_employee=sample_employee.id_employee,
        scheduled_at=datetime.now(timezone.utc) + timedelta(days=1),
        reason="Discuss account issue in detail",
        status=AppointmentStatus.PENDING
    )
    db_session.add(appointment)
    db_session.commit()
    return appointment


@pytest.fixture
def sample_appointment_accepted(
    db_session,
    sample_ticket_assigned,
    sample_customer,
    sample_employee
) -> Appointment:
    """Create an accepted appointment."""
    appointment = Appointment(
        id_appointment=uuid4(),
        id_ticket=sample_ticket_assigned.id_ticket,
        id_customer=sample_customer.id_customer,
        id_employee=sample_employee.id_employee,
        scheduled_at=datetime.now(timezone.utc) + timedelta(days=2),
        reason="Follow-up discussion",
        status=AppointmentStatus.ACCEPTED
    )
    db_session.add(appointment)
    db_session.commit()
    return appointment


# ============================================================================
# Interaction Fixtures
# ============================================================================

@pytest.fixture
def sample_message(
    db_session,
    sample_ticket,
    sample_customer
) -> Message:
    """Create a sample chat message."""
    message = Message(
        id_message=uuid4(),
        message="Hello, I need help with my account",
        message_type=MessageType.TEXT,
        is_read=False,
        is_deleted=False,
        id_ticket=sample_ticket.id_ticket,
        id_sender=sample_customer.id
    )
    db_session.add(message)
    db_session.commit()
    return message


@pytest.fixture
def sample_employee_message(
    db_session,
    sample_ticket,
    sample_employee
) -> Message:
    """Create a sample message from employee."""
    message = Message(
        id_message=uuid4(),
        message="Hello, how can I assist you today?",
        message_type=MessageType.TEXT,
        is_read=True,
        is_deleted=False,
        id_ticket=sample_ticket.id_ticket,
        id_sender=sample_employee.id
    )
    db_session.add(message)
    db_session.commit()
    return message


@pytest.fixture
def sample_evaluate(
    db_session,
    sample_ticket,
    sample_customer
) -> Evaluate:
    """Create a sample evaluation."""
    evaluate = Evaluate(
        id_evaluate=uuid4(),
        star=5,
        comment="Great support!",
        id_ticket=sample_ticket.id_ticket,
        id_customer=sample_customer.id_customer
    )
    db_session.add(evaluate)
    db_session.commit()
    return evaluate


# ============================================================================
# Chat Session Fixtures
# ============================================================================

@pytest.fixture
def sample_chat_session(
    db_session,
    sample_customer
) -> ChatSession:
    """Create a sample chatbot session."""
    session = ChatSession(
        id_session=uuid4(),
        customer_id=sample_customer.id_customer
    )
    db_session.add(session)
    db_session.commit()
    return session


# ============================================================================
# Mock Fixtures
# ============================================================================

@pytest.fixture
def mock_redis_service():
    """Mock Redis service for tests that need Redis operations."""
    with patch("app.services.redisService.redis_service") as mock:
        mock.get.return_value = None
        mock.set_with_expiry.return_value = True
        mock.delete.return_value = True
        mock.increment.return_value = 1
        mock.is_connected.return_value = True
        yield mock


@pytest.fixture
def mock_email_service():
    """Mock email service to prevent actual email sending during tests."""
    with patch("app.services.emailService.email_service") as mock:
        mock.send_otp_email.return_value = True
        mock.send_password_reset_otp_email.return_value = True
        mock.send_ticket_notification.return_value = True
        mock.send_csat_survey.return_value = True
        mock.send_email.return_value = True
        yield mock


@pytest.fixture
def mock_groq_service():
    """Mock Groq service for chatbot tests."""
    with patch("app.services.groqService.GroqService") as mock_class:
        mock_instance = mock_class.return_value
        mock_instance.chat.return_value = "I'm here to help! How can I assist you today?"
        yield mock_instance


@pytest.fixture
def mock_notification_service():
    """Mock notification service."""
    with patch("app.services.notificationService.NotificationService") as mock_class:
        mock_instance = mock_class.return_value
        mock_instance.create_and_send = MagicMock()
        yield mock_instance


# ============================================================================
# Helper Functions
# ============================================================================

def create_test_jwt_token(user: Human, token_type: str = "access") -> str:
    """
    Create a test JWT token for a user.
    Used for authentication testing.
    """
    import jwt
    from app.core.config import settings

    expire = datetime.utcnow() + timedelta(minutes=30) if token_type == "access" else timedelta(days=7)
    jti = str(uuid4())

    role = getattr(user, 'role_name', 'Customer') if user.type == 'employee' else 'Customer'

    payload = {
        "sub": str(user.id),
        "jti": jti,
        "email": user.email,
        "user_type": user.type,
        "role": role,
        "exp": expire,
        "type": token_type
    }

    return jwt.encode(payload, settings.JWT_SECRET, algorithm=settings.JWT_ALGORITHM)


def create_test_otp(email: str, otp_code: str = "123456") -> dict:
    """Create a test OTP entry in Redis."""
    import json
    return {
        "otp": otp_code,
        "data": None,
        "type": "verification"
    }


# ============================================================================
# Test Configuration
# ============================================================================

def pytest_configure(config):
    """Configure pytest with custom markers."""
    config.addinivalue_line(
        "markers", "integration: mark test as integration test (requires database)"
    )
    config.addinivalue_line(
        "markers", "unit: mark test as unit test (no external dependencies)"
    )
    config.addinivalue_line(
        "markers", "slow: mark test as slow running"
    )
    config.addinivalue_line(
        "markers", "auth: mark test as authentication test"
    )
    config.addinivalue_line(
        "markers", "ticket: mark test as ticket management test"
    )
    config.addinivalue_line(
        "markers", "chat: mark test as chat test"
    )
    config.addinivalue_line(
        "markers", "chatbot: mark test as chatbot test"
    )
    config.addinivalue_line(
        "markers", "appointment: mark test as appointment test"
    )