"""add is_read and message_type to Message

Revision ID: 21a778cc1f4f
Revises: cfde4dd50593
Create Date: 2026-03-25 11:11:00.126403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a778cc1f4f'
down_revision: Union[str, Sequence[str], None] = 'cfde4dd50593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('messages_id_sender_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'humans', ['id_sender'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_id_sender_fkey'), 'messages', 'humans', ['id_sender'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
