"""add avatar column to humans

Revision ID: 540e035e6c5a
Revises: 4b57fd7a6e32
Create Date: 2026-03-21 16:47:14.557658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540e035e6c5a'
down_revision: Union[str, Sequence[str], None] = '4b57fd7a6e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
