"""add department and auto_assign to ticket category

Revision ID: c8ef65d838e9
Revises: 540e035e6c5a
Create Date: 2026-03-24 09:39:15.308384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ef65d838e9'
down_revision: Union[str, Sequence[str], None] = '540e035e6c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tickets_category', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('tickets_category', sa.Column('auto_assign', sa.Boolean(), nullable=True, server_default='true'))
    op.execute("UPDATE tickets_category SET department = 'General' WHERE department IS NULL")
    op.alter_column('tickets_category', 'department', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets_category', 'auto_assign')
    op.drop_column('tickets_category', 'department')
    # ### end Alembic commands ###
