"""add_cascade_delete_constraints

Revision ID: cfde4dd50593
Revises: 2026_03_24_0001
Create Date: 2026-03-25 00:43:02.915200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfde4dd50593'
down_revision: Union[str, Sequence[str], None] = '2026_03_24_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_id_uploader_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'humans', ['id_uploader'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('audit_logs_id_employee_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'employees', ['id_employee'], ['id_employee'], ondelete='SET NULL')
    op.drop_constraint(op.f('customers_customer_type_fkey'), 'customers', type_='foreignkey')
    op.drop_constraint(op.f('customers_id_customer_fkey'), 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'humans', ['id_customer'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'customers', 'customer_type', ['customer_type'], ['type_name'], ondelete='SET NULL')
    op.create_index(op.f('ix_departments_id_department'), 'departments', ['id_department'], unique=False)
    op.drop_constraint(op.f('employees_id_employee_fkey'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('employees_id_department_fkey'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('employees_role_name_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'humans', ['id_employee'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employees', 'departments', ['id_department'], ['id_department'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'roles', ['role_name'], ['role_name'], ondelete='SET NULL')
    op.drop_constraint(op.f('evaluates_id_ticket_fkey'), 'evaluates', type_='foreignkey')
    op.drop_constraint(op.f('evaluates_id_customer_fkey'), 'evaluates', type_='foreignkey')
    op.create_foreign_key(None, 'evaluates', 'customers', ['id_customer'], ['id_customer'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluates', 'tickets', ['id_ticket'], ['id_ticket'], ondelete='CASCADE')
    op.drop_constraint(op.f('faq_articles_id_category_fkey'), 'faq_articles', type_='foreignkey')
    op.drop_constraint(op.f('faq_articles_id_author_fkey'), 'faq_articles', type_='foreignkey')
    op.create_foreign_key(None, 'faq_articles', 'tickets_category', ['id_category'], ['id_category'], ondelete='SET NULL')
    op.create_foreign_key(None, 'faq_articles', 'employees', ['id_author'], ['id_employee'], ondelete='SET NULL')
    op.drop_constraint(op.f('messages_id_sender_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_id_ticket_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'humans', ['id_sender'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'tickets', ['id_ticket'], ['id_ticket'], ondelete='CASCADE')
    op.drop_constraint(op.f('notification_id_receiver_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'humans', ['id_receiver'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('tickets_id_employee_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_id_category_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_id_customer_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'tickets_category', ['id_category'], ['id_category'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'employees', ['id_employee'], ['id_employee'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'customers', ['id_customer'], ['id_customer'], ondelete='CASCADE')
    op.drop_constraint(op.f('tickets_category_id_department_fkey'), 'tickets_category', type_='foreignkey')
    op.create_foreign_key(None, 'tickets_category', 'departments', ['id_department'], ['id_department'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets_category', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_category_id_department_fkey'), 'tickets_category', 'departments', ['id_department'], ['id_department'])
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_id_customer_fkey'), 'tickets', 'customers', ['id_customer'], ['id_customer'])
    op.create_foreign_key(op.f('tickets_id_category_fkey'), 'tickets', 'tickets_category', ['id_category'], ['id_category'])
    op.create_foreign_key(op.f('tickets_id_employee_fkey'), 'tickets', 'employees', ['id_employee'], ['id_employee'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_id_receiver_fkey'), 'notification', 'humans', ['id_receiver'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_id_ticket_fkey'), 'messages', 'tickets', ['id_ticket'], ['id_ticket'])
    op.create_foreign_key(op.f('messages_id_sender_fkey'), 'messages', 'humans', ['id_sender'], ['id'])
    op.drop_constraint(None, 'faq_articles', type_='foreignkey')
    op.drop_constraint(None, 'faq_articles', type_='foreignkey')
    op.create_foreign_key(op.f('faq_articles_id_author_fkey'), 'faq_articles', 'employees', ['id_author'], ['id_employee'])
    op.create_foreign_key(op.f('faq_articles_id_category_fkey'), 'faq_articles', 'tickets_category', ['id_category'], ['id_category'])
    op.drop_constraint(None, 'evaluates', type_='foreignkey')
    op.drop_constraint(None, 'evaluates', type_='foreignkey')
    op.create_foreign_key(op.f('evaluates_id_customer_fkey'), 'evaluates', 'customers', ['id_customer'], ['id_customer'])
    op.create_foreign_key(op.f('evaluates_id_ticket_fkey'), 'evaluates', 'tickets', ['id_ticket'], ['id_ticket'])
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_role_name_fkey'), 'employees', 'roles', ['role_name'], ['role_name'])
    op.create_foreign_key(op.f('employees_id_department_fkey'), 'employees', 'departments', ['id_department'], ['id_department'])
    op.create_foreign_key(op.f('employees_id_employee_fkey'), 'employees', 'humans', ['id_employee'], ['id'])
    op.drop_index(op.f('ix_departments_id_department'), table_name='departments')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_id_customer_fkey'), 'customers', 'humans', ['id_customer'], ['id'])
    op.create_foreign_key(op.f('customers_customer_type_fkey'), 'customers', 'customer_type', ['customer_type'], ['type_name'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_id_employee_fkey'), 'audit_logs', 'employees', ['id_employee'], ['id_employee'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_id_uploader_fkey'), 'attachments', 'humans', ['id_uploader'], ['id'])
    # ### end Alembic commands ###
