"""ticket_update

Revision ID: d2bafa43cfd0
Revises: d6e123456789
Create Date: 2026-04-11 00:59:11.971697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2bafa43cfd0'
down_revision: Union[str, Sequence[str], None] = 'd6e123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_comments',
    sa.Column('id_comment', sa.UUID(), nullable=False),
    sa.Column('id_ticket', sa.UUID(), nullable=False),
    sa.Column('id_author', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['humans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_comment')
    )
    op.create_index(op.f('ix_ticket_comments_id_comment'), 'ticket_comments', ['id_comment'], unique=False)
    op.create_table('ticket_history',
    sa.Column('id_history', sa.UUID(), nullable=False),
    sa.Column('id_ticket', sa.UUID(), nullable=False),
    sa.Column('id_actor', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_actor'], ['humans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_ticket'], ['tickets.id_ticket'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.create_index(op.f('ix_ticket_history_id_history'), 'ticket_history', ['id_history'], unique=False)
    op.drop_column('attachments', 'thumbnail_url')
    op.drop_column('attachments', 'is_permanent')
    op.drop_column('attachments', 'file_size')
    op.drop_column('attachments', 'is_deleted')
    op.drop_column('attachments', 'public_id')
    op.drop_column('attachments', 'storage_type')
    op.drop_column('attachments', 'attach_extension')
    op.drop_column('attachments', 'reference_type')
    op.drop_column('attachments', 'updated_at')
    op.drop_constraint(op.f('messages_id_sender_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'humans', ['id_sender'], ['id'], ondelete='SET NULL')
    op.add_column('tickets', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolution_note')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_id_sender_fkey'), 'messages', 'humans', ['id_sender'], ['id'], ondelete='SET NULL')
    op.add_column('attachments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('attach_extension', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('storage_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('public_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('is_permanent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ticket_history_id_history'), table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index(op.f('ix_ticket_comments_id_comment'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    # ### end Alembic commands ###
